### ISSUE TITLE
Infrastructure nodes don't get a proper container with "-format plantuml/c4plantuml"

### ISSUE THREAD

**Issue by sjbanner** [structurizr/export#14]
It works properly with plantuml, but with "plantuml/c4plantuml" the "Container(...)" line is missing so the Infrastructure Node shows up as a circle outside of any Deployment Nodes.

**Comment by simonbrowndotje** [comment]
This may have been fixed already by PR #8, but I don't think the current CLI version includes this change.

**Comment by sjbanner** [comment]
Thanks, any idea when we can expect the next CLI release?

**Comment by sjbanner** [comment]
I am building it in a Docker container, but that gives me enough to work with. There appear to be a couple of features in that PR that I would like, so it will be worth the effort. Thanks much.
