### ISSUE TITLE
Honor shapes in C4-Plantuml exporter

### ISSUE THREAD

**Issue by dgutson** [structurizr/export#21]
This is related to https://github.com/structurizr/export/issues/11 but not exactly.
Now that C4-Plantuml added the robot shape, it would be useful that the exporter honors the Robot shape in styles:
```
    views {
        styles {
            element "robot_user" {
                shape Robot
            }
        }
    }
```

That should be translated as the sprite "robot".

**Comment by dgutson** [comment]
@simonbrowndotje that's great!
Note that C4-Plantuml just added the robot shape (sprite) yesterday. Does this change anything?
https://github.com/plantuml-stdlib/C4-PlantUML/issues/244 where you did comment there.

**Comment by simonbrowndotje** [comment]
> Note that C4-Plantuml just added the robot shape (sprite) yesterday. Does this change anything?

No, that's actually how the above example works ... it's using one of the new robot sprites that were added yesterday.

**Comment by dgutson** [comment]
One more comment: I get the stereotype legend:
![image](https://user-images.githubusercontent.com/9671770/197574402-ca9433d3-dda6-4025-9b69-cf46ca0e9495.png)
I need to add `HIDE_STEREOTYPE()` to the plantuml to avoid it.

How do you do to not get it?

**Comment by simonbrowndotje** [comment]
> One more comment: I get the stereotype legend:

Please open a separate issue for the stereotype problem, and be sure to include enough information to reproduce it.

**Comment by dgutson** [comment]
I think something is broken, now despite I added the property `c4plantuml.tags`, tags are not added for Systems:
```
    views {
        properties {
            "c4plantuml.tags" "true"
            "plantuml.legend" "false"
        }
```

Generated:
```
Boundary(group_0, "Customer") {
  System(XXX, "YYY", "ZZZ", $tags="Software System")

```

I tried to add the tag both before the braces, and inside with `tags`.

Before this change, my tags showed up in the `$tags` string.

**Comment by simonbrowndotje** [comment]
It's hard to say what's going on without a full DSL example I'm afraid.

**Comment by dgutson** [comment]
test.dsl:
```
workspace "Test Product Architecture" "Model of the Test Platform." {

    !identifiers hierarchical

    model {
        group Customer {
            ees_user = person "EES users" "" "users"
            ends_user = person "ENDS user"
            frontend_user = person "FE user"
            webhooks_user = person "Webhooks User" "" "robot_user"
            EAS = softwaresystem "EAS" "Service1" {
                SP = container "Processor" "Something" "Node.js"
                engine = container "Engine" "Processes the data" "Go"

                SP -> engine "Sends data"
                engine -> SP "Send results"
            }

            backend = softwaresystem "Backend" "Backend1" "multi" {
                database = container "DB" "" "MongoDB" "DB"
                app = container "App" "Backend Server" "Node.js"

                app -> database "Uses"
            }

            backend.app -> EAS.SP "Send data"
            EAS.SP -> backend.app "Send results"
        }
    }

    views {
        properties {
            "plantuml.includes" "extra_styles.puml"
            "c4plantuml.tags" "true"
            "plantuml.legend" "false"
        }

        systemlandscape TheSystemLandscape {
            include *
            autoLayout
        }

        theme default

        styles {
            element "DB" {
                shape Cylinder
            }

            element "dataset" {
                background #006400
            }

            element "robot_user" {
                properties {
                    c4plantuml.sprite robot
                }
            }

            element "users" {
                properties {
                    c4plantuml.sprite users
                }
            }
        }
    }
}
```

stricturizr-TheSystemLandscape.puml:
```
@startuml
title System Landscape

top to bottom direction

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include extra_styles.puml

AddElementTag("Software System", $bgColor="#1168bd", $borderColor="#0b4884", $fontColor="#ffffff", $sprite="")
AddElementTag("Person,users", $bgColor="#08427b", $borderColor="#052e56", $fontColor="#ffffff", $sprite="users")
AddElementTag("Person,robot_user", $bgColor="#08427b", $borderColor="#052e56", $fontColor="#ffffff", $sprite="robot")
AddElementTag("Person", $bgColor="#08427b", $borderColor="#052e56", $fontColor="#ffffff", $sprite="")

AddRelTag("Relationship", $textColor="#707070", $lineColor="#707070")

Boundary(group_0, "Customer") {
  Person(EESusers, "EES users", "", $tags="Person,users")
  System(Backend, "Backend", "Backend1", $tags="Software System")
  Person(ENDSuser, "ENDS user", "", $tags="Person")
  Person(FEuser, "FE user", "", $tags="Person")
  Person(WebhooksUser, "Webhooks User", "", $tags="Person,robot_user")
  System(EAS, "EAS", "Service1", $tags="Software System")
}


Rel_D(Backend, EAS, "Send data", $tags="Relationship")
Rel_D(EAS, Backend, "Send results", $tags="Relationship")
@enduml
```

The tag "multi" does not show up in the .puml file.

Just for this to compile - extra_styles.puml:
```
@startuml

!define FONTAWESOME5 https://raw.githubusercontent.com/plantuml/plantuml-stdlib/master/tupadr3/font-awesome-5
!include FONTAWESOME5/users.puml

'do this only if we're generating C4-puml:
!if (%function_exists("AddElementTag"))
AddElementTag("multi", $shadowing="true")
HIDE_STEREOTYPE()
!endif
@enduml
```

**Comment by simonbrowndotje** [comment]
There's no element style for `multi` defined in your workspace, so it's being ignored. I've added support for an element style property named `c4plantuml.shadow`, for example:

```
element "multi" {
    properties {
        c4plantuml.shadow true
    }
}
```

**Comment by simonbrowndotje** [comment]
> Regarding the behavior, with a previous version (tag 0f71abe78aa8 built 9hs ago), there was no need for an element style to get the tag in the system:

Yes, I had to change this because there's a mismatch between how Structurizr treats tags vs how C4-PlantUML treats tags. Since this is an exporter from Structurizr, I decided to switch the semantics to better reflect how Structurizr deals with tags and styling, which provides a more consistent experience across the Structurizr renderer, the PlantUML exports, Mermaid export, etc. The old version used `+` to create a set of tags, whereas this new version creates a single tag based upon the tags/styles defined in the workspace. If this doesn't work for you, you may want to look at [this alternative C4-PlantUML exporter](https://github.com/cloudflightio/structurizr-export-c4plantuml) instead.

**Comment by dgutson** [comment]
It's fine, I have everything I need. I just thought that with the previous behavior, I was free to add as many `AddElementTag` as I needed in an external puml file. Now, you're right that this provides a better user experience at the cost of a little less flexibility.
My only need to add an external puml file is to provide additional includes for extra sprites (eg `users` from `font-awesome-5`) and to hide the legend (which I will file a separate issue these days).
