### ISSUE TITLE
accept plantuml.sequenceDiagrams in c4plantuml when set to false

### ISSUE THREAD

**Issue by dgutson** [structurizr/export#23]
Currently, the c4plantuml exporter gives an error when `plantuml.sequenceDiagrams` is used, no matter the value.
In order to be able to export the same DSL for both expoerters (plain plantuml and c4plantuml), please allow the property by considering the value: let c4plantuml exporter accept it if the property is set to `false`.

**Comment by dgutson** [comment]
Another option is to add the ability to add properties for specific exporters, eg
`properties * {` for all, and `properties "exporter1, exporter2, ..." {` for an exporters list.

**Comment by dgutson** [comment]
The current behavior is incosistent with other properties such as `c4plantuml.tags` where the plain plantuml exporter doesn't complain.

**Comment by simonbrowndotje** [comment]
> Currently, the c4plantuml exporter gives an error when plantuml.sequenceDiagrams is used, no matter the value.

This doesn't seem to be the case for me, at least with this workspace definition:

```
workspace {

    model {
        user = person "User"
        softwareSystem = softwareSystem "Software System"

        user -> softwareSystem "Uses"
    }

    views {
        properties {
            "plantuml.sequenceDiagrams" "false"
        }
        dynamic * {
            user -> softwareSystem
        }
    }
    
}
```

```
./structurizr.sh export -workspace test.dsl -format plantuml/c4plantuml
Exporting workspace from test.dsl
 - loading workspace from DSL
 - exporting with C4PlantUMLExporter
 - writing /usr/local/structurizr/structurizr-Dynamic-001.puml
 - finished
```

**Comment by dgutson** [comment]
I got this error with my .dsl, I'll try to simplify it:
```
 - exporting with C4PlantUMLExporter
java.lang.UnsupportedOperationException: Sequence diagrams are not supported by C4-PlantUML
        at com.structurizr.export.plantuml.C4PlantUMLExporter.export(C4PlantUMLExporter.java:239)
        at com.structurizr.export.AbstractDiagramExporter.export(AbstractDiagramExporter.java:64)
        at com.structurizr.cli.export.ExportCommand.run(ExportCommand.java:159)
        at com.structurizr.cli.StructurizrCliApplication.run(StructurizrCliApplication.java:77)
        at com.structurizr.cli.StructurizrCliApplication.main(StructurizrCliApplication.java:112)
```

**Comment by dgutson** [comment]
OK, today setting the property value to `false` works :) I will file a different issue for the properties depending on the exporter.
