### ISSUE TITLE
Enable views properties depending on the exporter

### ISSUE THREAD

**Issue by dgutson** [structurizr/export#25]
There are some exporter-specific properties.
And, some views are generated with different exporters.
That's why I suggest to be able to specify properties specific for each exporter, by adding the list of exporters next to the `properties` keyword (or `*` for all the exporters).
For example:
```
    views {
        properties * {
            plantuml.includes extra_styles.puml
            plantuml.legend false
        }

        properties "plantuml" {
            plantuml.sequenceDiagrams true
        }

        properties "plantuml/c4plantuml" {
            c4plantuml.tags true            
        }
    }
```

A more complete solution would be to be able to specify the exporter per view, as a property. I understand this might be more challenging. For example, I would like to generate the landscape view with c4plantuml, and the dynamic diagrams with plain plantuml.

**Comment by simonbrowndotje** [comment]
Although not quite the same, this is now better catered for by allowing properties to be defined at the view level.

**Comment by dgutson** [comment]
My use case is: I need to generate some diagrams with plantuml (eg sequence diagrams), others with C4-plantuml, from the same .dsl.
So, I run structurizr twice, and I have to implement a hack (including a generated dsl) to avoid the "plantuml.sequencediagram true" when exporting to C4-plantuml (in which case it pops an error because of the `true` value).
I could easily avoid that hack with the enhancement I propose here.

**Comment by dgutson** [comment]
ok thanks.
