### ISSUE TITLE
Extend the legend based on styles/tags

### ISSUE THREAD

**Issue by dgutson** [structurizr/export#31]
In order to avoid high textual pollution, I use different styles for technologies or special component "styles".
For example, a blue dashed arrow means https. It would be useful to add such custom notation to the legend (based on tags), for example by adding a property to the styles:
```
    styles {
        relationship "https" {
               c4plantuml.legend "HTTPS Connection"
         }
    }
```

**Comment by simonbrowndotje** [comment]
Support for dashed arrows was missing, so I've added it, and they will now show up in the legend as expected. Here's an example:

```
workspace {

    model {
        a = softwareSystem "A"
        b = softwareSystem "B"

        a -> b "Makes APIs calls using" {
            tags "HTTPS Connection"
        }
    }

    views {
        systemLandscape {
            include *
            autoLayout
        }
        
        properties {
            c4plantuml.tags true
        }

        styles {
            relationship "HTTPS Connection" {
                color #0000ff
                style dashed
            }
        }
    }
    
}
```

![image](https://user-images.githubusercontent.com/1009874/200766316-34ab177e-e0ef-484a-9770-19b330a5c392.png)

Dotted lines also work now too.

![image](https://user-images.githubusercontent.com/1009874/200768633-ca2ffe24-5f02-49d1-9ade-a37c97389aba.png)

**Comment by dgutson** [comment]
Awesome!
