### ISSUE TITLE
Allow "returning" arrows with different name in sequence diagrams

### ISSUE THREAD

**Issue by dgutson** [structurizr/export#32]
This is a spinoff of #30, particularly from the clarifying comment https://github.com/structurizr/export/issues/30#issuecomment-1309184774

Currently, structurizr shows "dotted" arrows in sequence diagrams when there exists a relationship with a certain name, and then the returning relation (inverted src/dest) with the same name.

I ask to allow returninig arrows with different names:
```
    a->b "send data"
    b->a "return results"
```

One possible solution is to create a new relationship style property:
```
relationship "return" {
    properties {
        sequence.return true
    }
}
```
so I would add the `return` tag in the relationships.

**Comment by simonbrowndotje** [comment]
This is not documented, because it's a feature that only a couple of people have ever asked for, and it's on the edge of what the C4 model and Structurizr was designed to support, but what you're asking is possible now; for example:

```
workspace {

    model {
        a = softwareSystem "A"
        b = softwareSystem "B"

        a -> b "send data"
    }

    views {
        dynamic * {
            a -> b
            b -> a "return results"
            
            properties {
                plantuml.sequenceDiagram true
            }
        }
    }
    
}
```

![image](https://user-images.githubusercontent.com/1009874/200926192-15393c8c-e2e1-4fb3-8397-19c6098d74e0.png)

In essence, because the `b -> a` relationship doesn't exist in the model, but `a -> b` does, it's determined to be a "response" message, and is rendered as such. It's a feature of the underlying Java client library, and you can read about it at:

- https://github.com/structurizr/java/pull/130
- https://github.com/structurizr/java/issues/153

**Comment by dgutson** [comment]
It does work for all the cases but one: when the "response" does exist in the model, I have no way of letting the exporter knokw that it is a response message. The only way I have is to play with its 'existence'.

**Comment by simonbrowndotje** [comment]
> I have no way of letting the exporter knokw that it is a response message. The only way I have is to play with its 'existence'.

That's correct. Based upon this and some of the other issues you've raised (relationship cardinality, interfaces, etc), you're skating on the edge of what the C4 model and Structurizr was designed to support, so you may find everything you're trying to do much easier by taking the C4 model concepts (abstractions + diagram types) and applying them to a UML tool, which by definition will have much richer semantics.

**Comment by dgutson** [comment]
I was afraid of that exactly answer :) I was discussing this with a colleague earlier today.
I'm "skating" in the edge between C4 and UML overlapping motivations.
So what I need is an integration between C4 and UML. I'm afraid I will need to address it as a separate tool.
I need C4 for certain levels of abstractions (and it is damn good for higher views) and UML for other levels. And they have to be consistent ("compile together"). I need to find such balance and smooth integration.

**Comment by simonbrowndotje** [comment]
> So what I need is an integration between C4 and UML.

You may want to look at something like [pumla](https://github.com/DrMarkusVoss/pumla), which provides a way to use C4-PlantUML in a model-based manner. Many of the "Visual modelling tools" listed at https://c4model.com/#Tooling have support for C4 and UML too.

**Comment by dgutson** [comment]
I still like structurizr's DSL. The DSL is by itself an added value besides the underlying model: it's higher level than plantUML, and even than C4-plantUML.
So it is not only about C4.
That's why I asked about the visualizer/exporter plugin in the other issue. If that will not be possible, we will have to proceed with a pre-processor of an "eDSL" (extended) that would generate both plantUML files and a structurizr DSL file. I want to avoid going there.

**Comment by simonbrowndotje** [comment]
I think building a pre-processor for your own DSL is the only option I'm afraid. As I've said before, we have a Slack group, so it would be worth checking that nobody has done something similar already.

**Comment by dgutson** [comment]
ok last attempt: would you accept a PR implementing https://github.com/structurizr/dsl/issues/174#issuecomment-1309778744 so structurizr DSL could be extensible? We already developed a structurizr DSL parser, and I could go to the "eDSL" approach, but I still think that by enhancing structurizr with a plugin-based view/exporter could be a win-win. I do prefer to contribute back to structurizr.

**Comment by simonbrowndotje** [comment]
Probably not. There's some crossover with [Support code diagrams #100](https://github.com/structurizr/structurizr/issues/100), so if anything was added, I'd rather it was done in a more general way, and in a way that provides easy integration with the Structurizr cloud service/Lite/on-premises installation, probably in conjunction with something like the [example PlantUML plugin](https://github.com/structurizr/dsl-plugins/tree/main/src/main/java/com/structurizr/dsl/plugins/plantuml). So it's on my radar, but not until 2023.

**Comment by simonbrowndotje** [comment]
This might be helpful too -> https://github.com/structurizr/dsl/issues/115

**Comment by dgutson** [comment]
Thanks, I contacted @juanrferia and see if we can collaborate. It seems we have both the same problem and the same principle of not dropping structurizr's DSL. I'll check what he did. Whatever I do, I'd like to benefit structurizr, so we will give any plugin to you so you may opt to use it in the cloud service/Lite/on-premises.
