### ISSUE TITLE
Different fonts in Linux and Mac

### ISSUE THREAD

**Issue by dgutson** [structurizr/export#41]
I think that the exporters should set the font name, or there should be a font property in the styles or theme in order to ensure that the same font is used everywhere.

This causes that renders look very different in some cases, to the point to cause word wrap, and turn diagrams difficult to compare.

**Comment by simonbrowndotje** [comment]
The [branding font](https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#branding) will now be used as the default font for the two PlantUML exporters.

(please note that you will need to build from source to use this library until it's released onto Maven Central)

**Comment by dgutson** [comment]
Thanks! How is the default font specified? Could you please add a note in the dsl reference, or provide an example?
Is using the `branding` body the only way to specify the font? Because I didn't find any other place where `font <name>` could be 
specified, not even in themes nor `styles`.

**Comment by simonbrowndotje** [comment]
Yes, via [branding](https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#branding), which is a child of [views](https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#views).

Example:

```
workspace {

    model {
        user = person "User"
    }

    views {
        branding {
            font Courier
        }
    }

}
```

You can also set it via Java, as shown in the [unit test](https://github.com/structurizr/export/commit/b206f46c3935ed541a3272d368ece93c97a66f0c#diff-fc7fc20787fa9c69363abef6fe58ab5feba8b07536be4662895bf2939b87c7d5R982).

Feel free to submit a docs PR if you think an example is needed.

**Comment by dgutson** [comment]
Last question, aligned with my previous question [here](https://github.com/structurizr/dsl/issues/201#issuecomment-1399512394), what is the default font name in Linux? IIUC, unless I explicit the font, I will still get different defaults in Linux and Mac, right?

**Comment by dgutson** [comment]
@simonbrowndotje any news about when this will be available in docker hub?

**Comment by dgutson** [comment]
ping? any update when this will be released?

**Comment by simonbrowndotje** [comment]
This particular code change was released onto Maven Central last week; see https://github.com/structurizr/export/releases for more details.

**Comment by bcordobaq** [comment]
Hi @simonbrowndotje, would it be possible that these changes aren't available yet in the Docker image? We've updated our project with the `branding` instruction, and we moved from `1.25.0` to the current latest `1.27.0`, and it didn't work... could you help me?
