### ISSUE TITLE
Use Plantuml stdlib C4 include syntax rather than Github URL based

### ISSUE THREAD

**Issue by MTomBosch** [structurizr/export#43]
At the moment when container or other diagrams are generated they C4 include directives are pointing to github URLs. 
At least in my use case my CI/CD system where I have integrated the exporter does not have Internet connection.
To make it work I have some patch script that replaces the link to Github by some local path. But this also means I have to keep the C4 puml files in my Git repo.

It would be much better if the C4 puml files would be referenced in "plantuml std lib" syntax, since all the C4 Puml files are part of the plantuml stdlib, see below for an example

https://plantuml.com/stdlib

```
@startuml
title My dummy title

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>
!include styles.puml

```

**Comment by simonbrowndotje** [comment]
This is mentioned in the docs -> https://github.com/structurizr/export/tree/main/src/main/java/com/structurizr/export/plantuml#c4plantumlexporter

**Comment by simonbrowndotje** [comment]
Also see #33
