### ISSUE TITLE
Show additional properties / details in deploymentNode diagrams

### ISSUE THREAD

**Issue by djjlewis** [structurizr/export#46]
I'm not sure the best place to put this, but I'm using Structurizr lite in a container so will go with here for now :-)

[C4-PlantUML](https://github.com/plantuml-stdlib/C4-PlantUML) allows for any number of Property attributes to be applied to a deployment node which can be useful for giving additional details (SKUs, sizing, IPs, hostnames etc) e.g.

```plantuml
SetPropertyHeader("Property","Value", "Description")
AddProperty("Prop1", "Value1", "Details1")
AddProperty("Prop2", "Value2", "Details2")
Deployment_Node_L(nodeAlias, "Label", "Optional Type", "Optional Description (with custom property header)") {

  WithoutPropertyHeader()
  AddProperty("PropC1", "ValueC1")
  AddProperty("PropC2", "ValueC2")
  Container(containerAlias, "Label", "Technology", "Optional Description (without property header)")
}
```

![image](https://user-images.githubusercontent.com/6518665/218261182-5d799f11-8e1b-42f8-b183-9e16507c1082.png)

I noticed that the deploymentNodes rendered in the deployment diagrams by Structurizr Lite (and the CLI export) only show the values from `name` and `technology`and anything else  is ignored / not rendered e.g. description

As a work around I can add anything of interest into `name` or `technology`, but do you think it would be useful to render a general set / table of properties similar to C4-PlantUML?

**Comment by simonbrowndotje** [comment]
Sure, PR merged ... thanks!
