### ISSUE TITLE
Internal property 'structurizr.dsl.identifier' on exported diagrams should be hidden

### ISSUE THREAD

**Issue by jp7677** [structurizr/export#49]
Hi there,

Commit https://github.com/structurizr/dsl/commit/0eda61d3555c53e7d382061fb0f8142c2eccc55f introduced the `structurizr.dsl.identifier` property. Unfortunately this property shows up on all elements when `"c4plantuml.elementProperties" "true"` is set in the view configuration. See e.g. at https://avisi-cloud.github.io/structurizr-site-generatr/main/internet-banking-system/context/

I think it would be nice if the exporter filters this (and may be future) internal property so that only properties from the model appear in the generated diagrams.

Kind regards

**Comment by simonbrowndotje** [comment]
All done. 👍

**Comment by jp7677** [comment]
Very cool, thanks for the very fast response!
