### ISSUE TITLE
shadow property for both plantuml exporters

### ISSUE THREAD

**Issue by dgutson** [structurizr/export#51]
currently we have `c4plantuml.shadow`

Could you please generalize this property for both exporters?

**Comment by dgutson** [comment]
@simonbrowndotje thank you so much!

Sorry if I did not explain myself.

By "generalize" I meant to have one sibgle property for both exporters, rather than two properties.
Maybe not a property but some keyword ("shadowed" or "shadow true").

I use the same .dsl to generate both C4 and plain plantUML and I have to conditionally generate one or the other at build time, unless I can set both properties at the same time and I won't get any error.

**Comment by simonbrowndotje** [comment]
Yes, you can set both properties at the same time.
