### ISSUE TITLE
Multiple groups with same name not rendered correctly (PlantUML)

### ISSUE THREAD

**Issue by chrikoch** [structurizr/export#57]
### Description

I have 2 software systems, each of them with a group "backend" and "frontend". When creating a dynamic view, containers of software system 2 are placed inside of software system 1 (probably because the groups in software system 1 have the same name).

When giving the groups different names (e.g. "backend software system 1") everything works as expected.

### Steps to reproduce

run code sample

### Screenshot

![grafik](https://user-images.githubusercontent.com/12702230/235663127-896b834b-14b3-47bf-a03d-3cfc7750fe54.png)

### Code sample

```text
workspace {
  model {
    s1 = softwareSystem "S1" {
      b1 = group "backend" {
        c1b = container "C1 Backend"
      }
      f1 = group "frontend" {
        c1f = container "C1 Frontend"
      }
      c1f -> c1b "call"
    }
    s2 = softwareSystem "S2" {
      b2 = group "backend" {
        c2b = container "C2 Backend"
      }
      f2 = group "frontend" {
        c2f = container "C2 Frontend"
      }
      c2f -> c2b "call"
    }
  }

  views {
    dynamic s2 test  {
      c1f -> c1b
      c2f -> c2b
  }
}
```

### Configuration

structurizr CLI 1.30.0 (via docker)

### Severity

Minor

### Priority

Low

### Resolution

I have no budget, please fix this for free

**Comment by simonbrowndotje** [comment]
I think this is a PlantUML issue, so you might want to raise it with them instead ... I can't get a simplified version to work either:

```
@startuml
set separator none

rectangle "A" {
  rectangle "group" {
    rectangle "B"
  }
}

rectangle "C" {
  rectangle "group" {
    rectangle "D" 
  }
}
@enduml
```

![image](https://user-images.githubusercontent.com/1009874/235843360-6d2f89dc-183a-4055-964f-f3bb3ec399c0.png)

If this syntax is incorrect, please let me know and I'll make a change to the exporter code.

**Comment by chrikoch** [comment]
Thanks for checking this. I've raised the question in the plantUML forum: https://forum.plantuml.net/17780/two-objects-with-same-name-rendered-only-once

However, I almost fear that it is intentional behavior. This very basic plantUML example also renders "A" only once:
```
@startuml
rectangle "A"
rectangle "B" 
rectangle "A"
@enduml
```

But I've found a workaround: When adding aliases, this works as expected:

```
@startuml
rectangle "A" {
  rectangle "group" as g1 {
    rectangle "B"
  }
}

rectangle "C " {
  rectangle "group" as g2 {
    rectangle "D"
  }
}
@enduml
```

**Comment by simonbrowndotje** [comment]
Closing as stale ... feel free to reopen in the future if necessary.
