### ISSUE TITLE
C4PlantUMLExporter mistakes container and component description for technologies when only description is present

### ISSUE THREAD

**Issue by pcolby** [structurizr/export#63]
### Description

The official [Structurizr DSL reference syntax for containers](https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#container) and [components](https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#component) is:

```
container <name> [description] [technology] [tags]
component <name> [description] [technology] [tags]
```

Though to be more precise, that is slightly ambiguous, and most Structurizr tooling interpret it as:

```
container <name> [description [technology [tags]]]
component <name> [description [technology [tags]]]
```

Which is to say, `tags` is the most-optional, followed-by `technology`, then `description`.  This can be seen in [ContainerParser::parse()](https://github.com/structurizr/dsl/blob/v1.30.1/src/main/java/com/structurizr/dsl/ContainerParser.java#L15) and [ComponentParser::parse()](https://github.com/structurizr/dsl/blob/v1.30.1/src/main/java/com/structurizr/dsl/ComponentParser.java#L15).

However, when [C4PlantUMLExporter::writeElement()](https://github.com/structurizr/export/blob/v1.14.0/src/main/java/com/structurizr/export/plantuml/C4PlantUMLExporter.java#L386) generates C4-PlantUML `Container(...)` and `Component(...)` procedure calls, if `technology` is not set, then `description` ends up in the `technology` argument's positional, and this `description` gets rendered as a `technology`.

### Steps to reproduce

1. Consider this example DSL:

```
workspace {
  model {
    enterprise "Demo" {
      demoSystem = softwaresystem "demoSystem" {
        demoContainer = container "demoContainer" "desc" "tech" "tags" {
          component "component1" "component1 description" "component1 technology" "component1 tag1,tsg2"
          component "component2" "component2 description" "component2 technology"
          component "component3" "component3 description" 
          component "component4"
        }
      }
    }
  }
  views {
    component demoContainer {
      include *
    }
   }
}
```

2. Render that via Structurizr, and C4-PlantUML, eg via https://structurizr.com/dsl

3. Observe that only `component3`, and only in the C4-PlantUML rendering, the `component3 description` text appears where the technology text should. See screenshots in the next section.

### Screenshot

Here's a sample show how it is correct for the Structurizr output, for all four components:

![image](https://github.com/structurizr/export/assets/5195222/f160f468-17e9-4c6e-b327-5f73c6d6c3fd)

And here, you can see how for the C4-PlantUML output, `component3`'s description appears in the technology position:

![image](https://github.com/structurizr/export/assets/5195222/0ec87ace-29ee-4789-b2fe-915b1c9c6b48)

### Code sample

```text
See "Steps to reproduce" above.
```

### Severity

Major

### Priority

Low

### Resolution

I'm willing to fix this myself and raise a PR

### More information

Looking at the generated C4-PlantUML (for the above sample DSL), it includes:

```
Container_Boundary("demoSystem.demoContainer_boundary", "demoContainer", $tags="") {
  Component(demoSystem.demoContainer.component1, "component1", "component1 technology", "component1 description", $tags="")
  Component(demoSystem.demoContainer.component2, "component2", "component2 technology", "component2 description", $tags="")
  Component(demoSystem.demoContainer.component3, "component3", "component3 description", $tags="")
  Component(demoSystem.demoContainer.component4, "component4", "", $tags="")
}
```

You can see that for `component3`, then description has shifted into the technology position.

For convenience, here are links to the relevant current C4-PlantUML procedure definitions:
* [Container](https://github.com/plantuml-stdlib/C4-PlantUML/blob/v2.6.0/C4_Container.puml#L72)
* [ContainerDb](https://github.com/plantuml-stdlib/C4-PlantUML/blob/v2.6.0/C4_Container.puml#L78)
* [ContainerQueue](https://github.com/plantuml-stdlib/C4-PlantUML/blob/v2.6.0/C4_Container.puml#L84)
* [Component](https://github.com/plantuml-stdlib/C4-PlantUML/blob/v2.6.0/C4_Component.puml#L65)
* [ComponentDb](https://github.com/plantuml-stdlib/C4-PlantUML/blob/v2.6.0/C4_Component.puml#L71)
* [ComponentQueue](https://github.com/plantuml-stdlib/C4-PlantUML/blob/v2.6.0/C4_Component.puml#L77)

And here's the code in `C4PlantUMLExporter.java` that writes (sometimes incorrectly) those procedure calls (ie this is where I'd say the fixes should go):
* [C4PlantUMLExporter::writeElement() - Container[Db|Queue]](https://github.com/structurizr/export/blob/v1.14.0/src/main/java/com/structurizr/export/plantuml/C4PlantUMLExporter.java#L450)
* [C4PlantUMLExporter::writeElement() - Component[Db|Queue]](https://github.com/structurizr/export/blob/v1.14.0/src/main/java/com/structurizr/export/plantuml/C4PlantUMLExporter.java#L457)

Note, the components fix will likely conflict with my existing open PR #60, so I would strongly recommend merging that PR (assuming you're happy with it) before fixing this. Or branch off my PR.

I'd be happy to have a go at fixing this bug too. Just not sure when I'll have time to get to it.

Cheers!

**Comment by simonbrowndotje** [comment]
Thanks ... given that the code in the exporter explicitly does something different for null/empty technologies, I'm guessing something has recently changed with PlantUML and/or C4-PlantUML to make this invalid ... especially since nobody has raised this before. I will merge your PR, then resolve this issue.
