### ISSUE TITLE
Support C4PlantUML borderStyle and borderThickness

### ISSUE THREAD

**Issue by qtzar** [structurizr/export#73]
### Description

C4 PlantUML V2.8.0 has added the capability to set the border style and border thickness on elements and boundaries.

I would like to be able to utilize these new values so that I can create new styles for tags like 'new' and 'depricated' so that I can produce future state diagrams that stand out from current state.

### Priority

Medium

### Resolution

I'm willing to add this feature myself and raise a PR

### More information

This looks like a simple enough change to add the two new properties to the export based on the current style ( similar to how borderColor is currently done ).

I will attempt a PR for the changes.

**Comment by qtzar** [comment]
May not be able to do this till the PlantUML library is updated to include the new C4 StdLib files.

**Comment by simonbrowndotje** [comment]
Thanks for the PR!
